name: Deploy Flask App to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: anujpawadia0125/flask-app:latest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to AKS
      env:
        KUBECONFIG: ${{ secrets.AKS_KUBECONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG" > $HOME/.kube/config
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl wait --for=condition=ready pod -l app=flask-app --timeout=60s
        # Verify deployment
        kubectl get deployments --namespace default
        kubectl describe deployment flask-app --namespace default
        kubectl logs -l app=flask-app
