name: Deploy Flask App to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: anujpawadia0125/flask-app:latest

    - name: Deploy to Minikube
      run: |
        # Note: Minikube must be running locally or in a controlled environment.
        # For GitHub Actions, this step assumes Minikube is accessible or skipped.
        # For local testing, apply these manually after pushing the image.
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl wait --for=condition=ready pod -l app=flask-app --timeout=60s
